version: '2'
services:
  server:
    image: codeview/server
    volumes:
     - ./server/local/:/src/code_view/settings/local/
    links:
     - redis
  client_web:
    image: codeview/client_web
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
     - ./redis/:/data/
  nginx:
    image: nginx
    ports:
     - 80:80
     - 443:443
    volumes_from:
     - client_web
    volumes:
     - ./nginx/:/etc/nginx/conf.d/
     - ./letsencrypt/:/letsencrypt/webroot/
     - /etc/letsencrypt/:/letsencrypt/keys/
    links:
     - server
