version: '2'
services:
  server:
    image: codeview/server
    volumes:
     - ./server/local/:/src/code_view/settings/local/
    links:
     - redis
  client_web:
    image: codeview/client_web
  redis:
    image: redis
    volumes:
     - ./redis/:/data/
  nginx:
    image: nginx
    ports:
     - 80:80
    volumes_from:
     - client_web
    volumes:
     - ./nginx/:/etc/nginx/conf.d/
    links:
     - server
